### ISSUE TITLE
国际化文件zh-CN.js dayOfMonth.title=月，应该为日

### ISSUE THREAD

**Issue by csccoder** [ldang264/vue-cron-generator#1]
# src/locale/zh-CN.js

 dayOfMonth: {
    timeUnit: '日',
    **title: '月',**
    val: '1 2...31'
  },

should update to

 dayOfMonth: {
    timeUnit: '日',
    title: '日',
    val: '1 2...31'
  },

**Comment by ldang264** [comment]
是的，这个我修复一下

**Comment by ldang264** [comment]
已发布0.1.6，修复了这个bug
https://github.com/ldang264/vue-cron-generator/releases/tag/v0.1.6
