### ISSUE TITLE
如何屏蔽掉秒和年的功能？

### ISSUE THREAD

**Issue by leizhu900516** [ldang264/vue-cron-generator#10]

**Comment by ldang264** [comment]
没有提供这块的开关，你可以下载源码定制哈

**Comment by lihuacai168** [comment]
> _No description provided._
麻烦问一下，这个功能后续面有实现吗？
求参考

**Comment by ldang264** [comment]
> > _No description provided._
> > 麻烦问一下，这个功能后续面有实现吗？
> > 求参考

这个是我的后端项目[attemper](https://github.com/attemper/attemper)
你用预览账号密码登进去以后，在调度管理-》任务管理，点选任务的触发器按钮，可以看到cron的使用

**Comment by lihuacai168** [comment]
> > > _No description provided._
> > > 麻烦问一下，这个功能后续面有实现吗？
> > > 求参考
> 
> 这个是我的后端项目[attemper](https://github.com/attemper/attemper)
> 你用预览账号密码登进去以后，在调度管理-》任务管理，点选任务的触发器按钮，可以看到cron的使用

感谢回复。
有点小尴尬，应该看错了，是后续，不是后端哦。
我想了解怎么去掉秒和年，因为标准的crontab没有这两项。
因为我这边用的后端定时任务，是基于标准crontab实现的

**Comment by ldang264** [comment]
> > > > _No description provided._
> > > > 麻烦问一下，这个功能后续面有实现吗？
> > > > 求参考
> > 
> > 
> > 这个是我的后端项目[attemper](https://github.com/attemper/attemper)
> > 你用预览账号密码登进去以后，在调度管理-》任务管理，点选任务的触发器按钮，可以看到cron的使用
> 
> 感谢回复。
> 有点小尴尬，应该看错了，是后续，不是后端哦。
> 我想了解怎么去掉秒和年，因为标准的crontab没有这两项。
> 因为我这边用的后端定时任务，是基于标准crontab实现的

这个建议你自己fork然后改，去掉这两个vue组件的引入，改下配置啥的就行了
