### ISSUE TITLE
请问下怎么切换成英文的

### ISSUE THREAD

**Issue by SincerelyUnique** [ldang264/vue-cron-generator#11]
您好，请问一下国际化这块怎么切换为英文的

**Comment by ldang264** [comment]
> 您好，请问一下国际化这块怎么切换为英文的

默认是根据浏览器的本地化切换的，如果不行的话，可以将下面的getLocale()改成en
`i18n = new VueI18n({
  // set locale
  // options: en | zh
    locale: getLocale(),
    // set locale messages
    messages
  })`

**Comment by ldang264** [comment]
> > 您好，请问一下国际化这块怎么切换为英文的
> 
> 默认是根据浏览器的本地化切换的，如果不行的话，可以将下面的getLocale()改成en
> `i18n = new VueI18n({ // set locale // options: en | zh locale: getLocale(), // set locale messages messages })`

不好意思，显式指定英文，应该把getLocale()改成'en_US'， README也更新了

**Comment by SincerelyUnique** [comment]
好的，非常感谢哈，我们时这样改的:

```
localStorage.setItem('locale','en-US')
import i18n from './lang'
```

当时一开始好像也是把getLocale()改成'en_US'，改过后有一个选择星期几的那边显示的还是中文，其他的正常都变成英文了，然后看了下您这边的code，看到组件里面还有一次国际化，也就是外面的国际化里面又套了一层国际化（node_modules\vue-cron-generator\src\locale\index.js），我们使用的时候只能改外面的，里面的改不了, 所以先手动塞到localStorage里

**Comment by ldang264** [comment]
> 好的，非常感谢哈，我们时这样改的:
> 
> ```
> localStorage.setItem('locale','en-US')
> import i18n from './lang'
> ```
> 
> 当时一开始好像也是把getLocale()改成'en_US'，改过后有一个选择星期几的那边显示的还是中文，其他的正常都变成英文了，然后看了下您这边的code，看到组件里面还有一次国际化，也就是外面的国际化里面又套了一层国际化（node_modules\vue-cron-generator\src\locale\index.js），我们使用的时候只能改外面的，里面的改不了, 所以先手动塞到localStorage里

客气啦
