### ISSUE TITLE
周中只能使用？不能使用其他字符

### ISSUE THREAD

**Issue by yhxjack** [ldang264/vue-cron-generator#14]
![image](https://user-images.githubusercontent.com/28732417/155954345-cccc0b04-8af1-4930-be64-e49c838f3890.png)

**Comment by ldang264** [comment]
@yhxjack 这是个语法的问题。当日=*的时候，代表了当月的每一天，周自然就不能用具体的配置了

**Comment by yhxjack** [comment]
那是否可以直接将周中的选项进行固定呢？因为此处能够选择，用户就会认为这是可定义的，可选择的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ldang264/vue-cron-generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 晚上6:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ldang264/vue-cron-generator] 周中只能使用？不能使用其他字符 (Issue #14)





 
@yhxjack 这是个语法的问题。当日=*的时候，代表了当月的每一天，周自然就不能用具体的配置了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ldang264** [comment]
@yhxjack 日配成?的时候，周可以使用一些具体配置。如果有特殊需求，你可以fork去改。。。

**Comment by yhxjack** [comment]
嗯嗯，感谢作者，我正在定制

**Comment by ldang264** [comment]
> 客气了
