### ISSUE TITLE
感觉最近10次的执行时刻可以安排一个开关来展示

### ISSUE THREAD

**Issue by yhxjack** [ldang264/vue-cron-generator#15]
![image](https://user-images.githubusercontent.com/28732417/155964525-39f59bd1-9323-4d24-81f7-45dbf14c597b.png)
首先，感谢作者大大写了这么好的组件，真的是省了很多事。但是目前如果直接引用的话，还需要自己定制。其实我感觉作者大大可以将框中的两个部分拆分成组件，然后通过开关控制呢？这样就可以直接使用这个组件，完全不需要定制了。

**Comment by ldang264** [comment]
@yhxjack vue-cron-generator这个组件是不包括计算cron的执行时间的，最近十次其实是demo（我是调用自己的[任务调度服务](https://github.com/attemper/attemper)实现的），所以其实已经是两个组件了

**Comment by yhxjack** [comment]
> 

但是master分支上源码没有分离啊，如果我直接引用的话，出现的就是上图。我觉得最近10次执行时刻挺好用的，可以单独抽一个服务出来，这样其他人可以直接引用

**Comment by ldang264** [comment]
@yhxjack 是的，并没有分离，我是直接在App.vue中调的，你可以自己参考去DIY下。最近10次这个，只是为了展示vue-cron-generator的展示效果，如果你了解Quartz之类的框架，调一行API就可以实现了

**Comment by yhxjack** [comment]
我自己写了一个获取最近执行时间的后端接口，因为依赖外部服务是不太稳定的，只是这个执行时间的展示蛮好的

**Comment by yhxjack** [comment]
我回头有时间把我改的提个pr，希望能帮到更多人

**Comment by ldang264** [comment]
> 我回头有时间把我改的提个pr，希望能帮到更多人

👍
