### ISSUE TITLE
Cannot find module './en-US.js'

### ISSUE THREAD

**Issue by kajtezdino** [ldang264/vue-cron-generator#2]
The **getLocale** method is causing this error as it checks in local storage for key 'locale' and if it is not set then uses navigator.systemLanguage or navigator.language. As this returns en-Us as system language this causes an error because module en-Us.js does not exist and for some apps, it is not that easy to modify the logic to suit these checks. Can you please make a change to avoid this check? 

You can see this error also on vue-cron-generator demo page.

**Comment by ldang264** [comment]
I see if I using Safari in MacOS,I will fix it in April.
Thank you for your feedback.

**Comment by ldang264** [comment]
Please use 0.1.6
https://github.com/ldang264/vue-cron-generator/releases/tag/v0.1.6
