### ISSUE TITLE
hola amigo este componente funciona pero no traduce los labels del componente.. te has fijado?

### ISSUE THREAD

**Issue by deylyn** [ldang264/vue-cron-generator#3]
<img width="1280" alt="Captura de pantalla 2020-04-29 a la(s) 6 10 53 p  m" src="https://user-images.githubusercontent.com/24438895/80651917-cf62f680-8a44-11ea-91f2-5fe257f9b5a3.png">

**Comment by ldang264** [comment]
Hi, the `vue-cron-generator` now only supports languages like en-US and zh_CN.
