### ISSUE TITLE
errores en el componente

### ISSUE THREAD

**Issue by deylyn** [ldang264/vue-cron-generator#4]
hola te has dado cuenta de los errores que salen cuando estas en la opción de dayOfweek(Week)

chunk-vendors.16721aa0.js:7 TypeError: Cannot read property 'min' of null
    at set [as tag_] (app.15eb2311.js:1)
    at s.tag (app.15eb2311.js:1)
    at rn.run (chunk-vendors.16721aa0.js:7)
    at Jt (chunk-vendors.16721aa0.js:7)
    at Array.<anonymous> (chunk-vendors.16721aa0.js:7)
    at tt (chunk-vendors.16721aa0.js:7)

<img width="1280" alt="Captura de pantalla 2020-05-13 a la(s) 4 43 56 p  m" src="https://user-images.githubusercontent.com/24438895/81863292-f9ceac80-9538-11ea-9cb4-fadcb0cd0937.png">

y también hay otro error cuando estas en la opción dayOfMonth(Day)
 da siempre un 
common.numError: cuando estas en la opción numero 6(últimos días del mes actual)

y deja que llegues hasta 11

<img width="1280" alt="Captura de pantalla 2020-05-13 a la(s) 4 50 21 p  m" src="https://user-images.githubusercontent.com/24438895/81863871-dbb57c00-9539-11ea-8de5-8568318c7e24.png">

**Comment by ldang264** [comment]
Hi,set your bowser's language to en_US and try it again
