### ISSUE TITLE
帮助里面的“每周一12点”应该是'0 0 12 ? * 2' ，而不是现在的'0 0 12 * * 2'

### ISSUE THREAD

**Issue by xianxianweid** [ldang264/vue-cron-generator#6]
这个问题还挺严重的，可以修复一下吗？

**Comment by ldang264** [comment]
我看了下，确实是bug，将在这周修复下并发布到npm

**Comment by ldang264** [comment]
> 这个问题还挺严重的，可以修复一下吗？

我看了下，确实是bug，将在这周修复下并发布到npm

**Comment by ldang264** [comment]
> 这个问题还挺严重的，可以修复一下吗？

已修复，请使用0.1.7版本
https://github.com/ldang264/vue-cron-generator/releases/tag/v0.1.7

**Comment by xianxianweid** [comment]
> > 这个问题还挺严重的，可以修复一下吗？
> 
> 已修复，请使用0.1.7版本
> https://github.com/ldang264/vue-cron-generator/releases/tag/v0.1.7

已验证，感谢。

**Comment by ldang264** [comment]
> > > 这个问题还挺严重的，可以修复一下吗？
> > 
> > 
> > 已修复，请使用0.1.7版本
> > https://github.com/ldang264/vue-cron-generator/releases/tag/v0.1.7
> 
> 已验证，感谢。

客气了
