### ISSUE TITLE
日选项卡本月倒数第几日存在BUG

### ISSUE THREAD

**Issue by ssc7618** [ldang264/vue-cron-generator#7]
日选项卡，第6项设置本月倒数第几天，点击增加天数，会提示含有非法数字，应该是字符串截取有问题，希望能修复一下

**Comment by ldang264** [comment]
已修复，请使用v0.1.8
https://github.com/ldang264/vue-cron-generator/releases/tag/v0.1.8

**Comment by ldang264** [comment]
> 日选项卡，第6项设置本月倒数第几天，点击增加天数，会提示含有非法数字，应该是字符串截取有问题，希望能修复一下

已修复，请使用v0.1.8
https://github.com/ldang264/vue-cron-generator/releases/tag/v0.1.8

**Comment by ssc7618** [comment]
好的，非常感谢！
