### ISSUE TITLE
后期有没有做看输出时间的需求？

### ISSUE THREAD

**Issue by cshenger** [ldang264/vue-cron-generator#8]
就是我想看到自己输入的字段后所匹配的时间是不是正确的，在当前这个版本下怎样改造？因为corn这个东西我不是很懂，所以想询问一下，或者后期开发团队有没有打算做展示匹配时间这个需求的计划？谢谢。
大概就像这样
![微信截图_20201207185852](https://user-images.githubusercontent.com/5855865/101343005-4f481d80-38be-11eb-90b2-556810d882c7.png)

**Comment by ldang264** [comment]
> 就是我想看到自己输入的字段后所匹配的时间是不是正确的，在当前这个版本下怎样改造？因为corn这个东西我不是很懂，所以想询问一下，或者后期开发团队有没有打算做展示匹配时间这个需求的计划？谢谢。
> 大概就像这样
> ![微信截图_20201207185852](https://user-images.githubusercontent.com/5855865/101343005-4f481d80-38be-11eb-90b2-556810d882c7.png)

这个要后端实现的

**Comment by yhxjack** [comment]
使用这个作者后端服务有个顾虑就是：这个后端服务挂了或者不维护了，我们就看不到最近10次的运行时间了，这个有办法优化吗
